// Code generated by "stringer -type=tokenType"; DO NOT EDIT.

package zonefile

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[tokenError-0]
	_ = x[tokenEOF-1]
	_ = x[tokenWhiteSpace-2]
	_ = x[tokenLeftParen-3]
	_ = x[tokenRightParen-4]
	_ = x[tokenComment-5]
	_ = x[tokenItem-6]
	_ = x[tokenQuotedItem-7]
	_ = x[tokenNewline-8]
}

const _tokenType_name = "tokenErrortokenEOFtokenWhiteSpacetokenLeftParentokenRightParentokenCommenttokenItemtokenQuotedItemtokenNewline"

var _tokenType_index = [...]uint8{0, 10, 18, 33, 47, 62, 74, 83, 98, 110}

func (i tokenType) String() string {
	if i < 0 || i >= tokenType(len(_tokenType_index)-1) {
		return "tokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _tokenType_name[_tokenType_index[i]:_tokenType_index[i+1]]
}
